config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "home#index"
  resources :home
  resources :archive do
    collection do
      get 'search'
    end
  end
  resources :clip
  resources :fanart
  resources :music
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/archive.rb
class Archive < ApplicationRecord
  has_many :tag_relations, dependent: :destroy
  has_many :tags, through: :tag_relations

  def self.search(search)
    if search != ""
      Archive.where('archivetitle LIKE(?)', "%#{search}%")
    else
      Archive.all
    end
  end
end

app/models/clip.rb
class Clip < ApplicationRecord
end

app/models/fanart.rb
class Fanart < ApplicationRecord
end

app/models/music.rb
class Music < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_relations, dependent: :destroy
  has_many :archives, through: :tag_relations
end

app/models/tag_relation.rb
class TagRelation < ApplicationRecord
  belongs_to :archive
  belongs_to :tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/archive_controller.rb
class ArchiveController < ApplicationController
  def index
    @archive = params[:tag_id].present? ? Tag.find(params[:tag_id]).archives.page(params[:page]).per(15) : Archive.all.page(params[:page]).per(15)
    @tag = Tag.all
  end

  def search
    @archives = Archive.search(params[:keyword]).page(params[:page]).per(15)
  end
end

app/controllers/clip_controller.rb
class ClipController < ApplicationController
  def index
    @clip = Clip.all.page(params[:page]).per(15)
  end
end

app/controllers/fanart_controller.rb
class FanartController < ApplicationController
  def index
    @fanart = Fanart.all.page(params[:page]).per(15)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @archivetop = Archive.order(archiveviews: :desc).limit(14)
    @cliptop = Clip.order("rand()").limit(14)
    @fanarttop = Fanart.order("rand()").limit(14)
  end
end

app/controllers/music_controller.rb
class MusicController < ApplicationController
  def index
    @music = Music.order("rand()").page(params[:page]).per(15)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def new
    @tag = Tag.all
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archive_helper.rb
module ArchiveHelper
end

app/helpers/clip_helper.rb
module ClipHelper
end

app/helpers/fanart_helper.rb
module FanartHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/music_helper.rb
module MusicHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/archive/_archive.html.erb
  <div class = "archive_card">
    <%= link_to "#{archive.archiveurl}",:onclick=>"window.open(this.href,'#{archive.archiveurl}', 'height=400, width=800');return false;" do %>
      <%= image_tag (archive.archiveimg) , class: :music_img %>
    <% end %>
    <p><%= archive.archivetitle %></p>
  </div>

app/views/archive/_result.html.erb
  <div class = "archive_card">
    <%= link_to "#{result.archiveurl}",:onclick=>"window.open(this.href,'#{result.archiveurl}', 'height=400, width=800');return false;" do %>
      <%= image_tag (result.archiveimg) , class: :music_img %>
    <% end %>
    <p><%= result.archivetitle %></p>
  </div>

app/views/archive/index.html.erb
<body class="is-preload">

<!-- Wrapper -->
	<div id="wrapper">

		<!-- Main -->
			<div id="main">
				<!-- news -->
				<!-- about-->
				<!-- archives -->
					<article id="archives">
						<ul class="actions">
            	<li><%= link_to 'HOME' , root_path , class: :button %></li>
            </ul>
						<h2 class="major">Archives</h2>
						<h3>オススメ動画</h3>
						<div class="archive">
							<%= render partial: "archive" , collection: @archive %>
						</div>
						<%= paginate @archive %>
						<ul class="actions">
            	<li><%= link_to 'HOME' , root_path , class: :button %></li>
            </ul>
					</article>
				<!-- fanarts -->
			</div>
			<ul class="icons">
				<li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
				<li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
				<li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
			</ul>
		<!-- Footer -->
			<footer id="footer">
				<p>ホロライブ所属アイドルVTuber 桃鈴ねねさんの⾮公式ファンサイトです。<br>
					カバー株式会社様、およびホロライブプロダクションとは⼀切関係ありません。
				<br>当サイトで使⽤している画像の著作権・肖像権等は各権利者に帰属いたします。</p>
			</footer>

	</div>

<!-- BG -->
	<div id="bg"></div>

<!-- Scripts -->

	<!--<script src="assets/js/jquery.min.js"></script>
	<script src="assets/js/browser.min.js"></script>
	<script src="assets/js/breakpoints.min.js"></script>
	<script src="assets/js/util.js"></script>
	<script src="assets/js/main.js"></script>-->

</body>

app/views/archive/search.html.erb
<body class="is-preload">

<!-- Wrapper -->
	<div id="wrapper">

		<!-- Main -->
			<div id="main">
				<!-- news -->
				<!-- about-->
				<!-- archives -->
					<article id="archives">
						<ul class="actions">
            	<li><%= link_to 'HOME' , root_path , class: :button %></li>
            </ul>
						<%= form_with(url: search_archive_index_path, local: true, method: :get) do |form| %>
  					<%= form.text_field :keyword, placeholder: "アーカイブを検索する" %>
  					<%= form.submit "検索" %>
						<% end %>
						<h2 class="major">Archives</h2>
						<h3>検索結果</h3>
						<div class="archive">
							<%= render partial: "result" , collection: @archives %>
						</div>
						<ul class="actions">
						<%= paginate @archives %>
            	<li><%= link_to 'HOME' , root_path , class: :button %></li>
            </ul>
					</article>
				<!-- fanarts -->
			</div>
			<ul class="icons">
				<li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
				<li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
				<li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
			</ul>
		<!-- Footer -->
			<footer id="footer">
				<p>ホロライブ所属アイドルVTuber 桃鈴ねねさんの⾮公式ファンサイトです。<br>
					カバー株式会社様、およびホロライブプロダクションとは⼀切関係ありません。
				<br>当サイトで使⽤している画像の著作権・肖像権等は各権利者に帰属いたします。</p>
			</footer>

	</div>

<!-- BG -->
	<div id="bg"></div>

<!-- Scripts -->

	<!--<script src="assets/js/jquery.min.js"></script>
	<script src="assets/js/browser.min.js"></script>
	<script src="assets/js/breakpoints.min.js"></script>
	<script src="assets/js/util.js"></script>
	<script src="assets/js/main.js"></script>-->

</body>

app/views/clip/_clip.html.erb
  <div class = "archive_card">
    <%= link_to "#{clip.clipurl}",:onclick=>"window.open(this.href,'#{clip.clipurl}', 'height=400, width=800');return false;" do %>
      <%= image_tag (clip.clipimg) , class: :music_img %>
    <% end %>
    <p><%= clip.cliptitle %></p>
  </div>

app/views/clip/index.html.erb
<body class="is-preload">

<!-- Wrapper -->
	<div id="wrapper">

		<!-- Main -->
			<div id="main">
				<!-- news -->
				<!-- about-->
				<!-- archives -->
					<article id="clip">
						<ul class="actions">
            	<li><%= link_to 'HOME' , root_path , class: :button %></li>
            </ul>
						<h2 class="major">clips</h2>
						<h3>オススメ動画</h3>
						<div class="archive">
							<%= render partial: "clip" , collection: @clip %>
						</div>
						<%= paginate @clip %>
						<ul class="actions">
            	<li><%= link_to 'HOME' , root_path , class: :button %></li>
            </ul>
					</article>
				<!-- fanarts -->
			</div>
			<ul class="icons">
				<li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
				<li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
				<li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
			</ul>
		<!-- Footer -->
			<footer id="footer">
				<p>ホロライブ所属アイドルVTuber 桃鈴ねねさんの⾮公式ファンサイトです。<br>
					カバー株式会社様、およびホロライブプロダクションとは⼀切関係ありません。
				<br>当サイトで使⽤している画像の著作権・肖像権等は各権利者に帰属いたします。</p>
			</footer>

	</div>

<!-- BG -->
	<div id="bg"></div>

<!-- Scripts -->

	<!--<script src="assets/js/jquery.min.js"></script>
	<script src="assets/js/browser.min.js"></script>
	<script src="assets/js/breakpoints.min.js"></script>
	<script src="assets/js/util.js"></script>
	<script src="assets/js/main.js"></script>-->

</body>

app/views/fanart/_fanart.html.erb
<blockquote class="twitter-tweet tw-align-center" data-theme="dark">
<a href= <%= "#{fanart.fanarturl}" %>></a>
</blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

app/views/fanart/index.html.erb
<body class="is-preload">

<!-- Wrapper -->
	<div id="wrapper">

		<!-- Main -->
			<div id="main">
				<!-- news -->
				<!-- about-->
				<!-- archives -->
					<article id="archives">
						<ul class="actions">
            	<li><%= link_to 'HOME' , root_path , class: :button %></li>
            </ul>

						<h2 class="major">fanart</h2>
							<%= render partial: "fanart" , collection: @fanart %>
						<%= paginate @fanart %>
						<ul class="actions">
            	<li><%= link_to 'HOME' , root_path , class: :button %></li>
            </ul>
					</article>
				<!-- fanarts -->
			</div>
			<ul class="icons">
				<li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
				<li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
				<li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
			</ul>
		<!-- Footer -->
			<footer id="footer">
				<p>ホロライブ所属アイドルVTuber 桃鈴ねねさんの⾮公式ファンサイトです。<br>
					カバー株式会社様、およびホロライブプロダクションとは⼀切関係ありません。
				<br>当サイトで使⽤している画像の著作権・肖像権等は各権利者に帰属いたします。</p>
			</footer>

	</div>

<!-- BG -->
	<div id="bg"></div>

<!-- Scripts -->

	<!--<script src="assets/js/jquery.min.js"></script>
	<script src="assets/js/browser.min.js"></script>
	<script src="assets/js/breakpoints.min.js"></script>
	<script src="assets/js/util.js"></script>
	<script src="assets/js/main.js"></script>-->

</body>

app/views/home/_archivetop.html.erb
<div class = "archive_card">
  <%= link_to "#{archivetop.archiveurl}",:onclick=>"window.open(this.href,'#{archivetop.archiveurl}', 'height=400, width=800');return false;" do %>
    <%= image_tag (archivetop.archiveimg) , class: :music_img %>
  <% end %>
  <p><%= archivetop.archivetitle %></p>
</div>

app/views/home/_cliptop.html.erb
<div class = "archive_card">
  <%= link_to "#{cliptop.clipurl}",:onclick=>"window.open(this.href,'#{cliptop.clipurl}', 'height=400, width=800');return false;" do %>
    <%= image_tag (cliptop.clipimg) , class: :music_img %>
  <% end %>
  <p><%= cliptop.cliptitle %></p>
</div>

app/views/home/_fanarttop.html.erb
<blockquote class="twitter-tweet tw-align-center" data-theme="dark">
<a href= <%= "#{fanarttop.fanarturl}" %>></a>
</blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

app/views/music/_music.html.erb
  <div class = "archive_card">
    <%= link_to "#{music.musicurl}",:onclick=>"window.open(this.href,'#{music.musicurl}', 'height=400, width=800');return false;" do %>
      <%= image_tag (music.musicimg) , class: :music_img %>
    <% end %>
    <p><%= music.musictitle %><br><%= music.musicauthor %></p>
  </div>

app/views/music/index.html.erb
<body class="is-preload">

<!-- Wrapper -->
	<div id="wrapper">

		<!-- Main -->
			<div id="main">
				<!-- news -->
				<!-- about-->
				<!-- archives -->
					<article id="archives">
          	<ul class="actions">
            	<li><%= link_to 'HOME' , root_path , class: :button %></li>
            </ul>
						<h2 class="major">MUSICS</h2>
						<h3>歌枠の動画をまとめてます</h3>
						<div class="archive">
							<%= render partial: "music" , collection: @music %>
						</div>
						<%= paginate @music %>
            <ul class="actions">
            	<li><%= link_to 'HOME' , root_path , class: :button %></li>
            </ul>
					</article>
				<!-- fanarts -->
			</div>
			<ul class="icons">
				<li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
				<li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
				<li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
			</ul>
		<!-- Footer -->
			<footer id="footer">
				<p>ホロライブ所属アイドルVTuber 桃鈴ねねさんの⾮公式ファンサイトです。<br>
					カバー株式会社様、およびホロライブプロダクションとは⼀切関係ありません。
				<br>当サイトで使⽤している画像の著作権・肖像権等は各権利者に帰属いたします。</p>
			</footer>

	</div>

<!-- BG -->
	<div id="bg"></div>

<!-- Scripts -->

	<!--<script src="assets/js/jquery.min.js"></script>
	<script src="assets/js/browser.min.js"></script>
	<script src="assets/js/breakpoints.min.js"></script>
	<script src="assets/js/util.js"></script>
	<script src="assets/js/main.js"></script>-->

</body>